claraferraz/justconnect-front

- src/interface/UserInterface.ts
- src/pages/RegisterPage/RegisterPage.tsx
- [ x] New feature (non-breaking change which adds functionality)
Foi realizado a estilização da página de login implementado todos os links para o fluxo de criação de usuario.
- Criação da tela de Registro
- [x ] My changes have less than or equal 400 lines
- [x ] I have performed a self-review of my own code
- [x ] The existing tests and linter pass locally with my changes
- npm install
> style: estilização da página de registro

- src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
Foi realizado a estilização da página de recuperação de senha utilizando chakra ui com base no login e no registro.
- Criação da tela de Forgot-Password
- npm install
> style: estilização da página de forgot

- package-lock.json
- package.json
- src/components/Sidebar/Sidebar.tsx
- src/interface/UserInterface.ts
- src/pages/LoginPage/LoginPage.tsx
- src/pages/RegisterPage/RegisterPage.tsx
- src/service/Auth.ts
Atualização no do sidebar e do header para ficar de acordo com as especificações do figma, também foi adicionado toast para a confirmação de registro e login bem sucedidos. Ajuste como posicionamento do toast ou utilizar outras libs como toastify serão opções discutidas posteriormente com a equipe. A integração do get para alterar o botão d login em um avatar será introduzida posteriormente.
- Criar o componente Header;
- Criar o componente Navbar;
- npm install
> Criação da sidebar de desktop e atualização do modelo do header.

- package-lock.json
- package.json
- src/components/Sidebar/MobileNav.tsx
- src/components/Sidebar/NavItem.tsx
- src/components/Sidebar/Sidebar.tsx
- src/components/Sidebar/SidebarContent.tsx
- src/components/Sidebar/SidebarHeader.tsx
- src/components/Sidebar/linkItems.ts
- src/interface/UserInterface.ts
- src/pages/LoginPage/LoginPage.tsx
- src/pages/RegisterPage/RegisterPage.tsx
- src/service/Auth.ts
- Foi realizada a integração da rota public/users/:id para captar dados do usuário que acabou de logar;
- Foi criado os métodos para que o botão de sair apenas apareça quando o usuário estiver logado;
- Ao usuário logar o botão de login é substituido por um icon de notificação e seu avatar com suas iniciais e cor de fundo.
- O arquivo sidebar agora é um componente pai e é nele que a integração está sendo passada para os outros componentes. Por exemplo, SidebarContent está recebendo user para que o botão de sair possa desaparecer quando não tiver um logado e SidebarHeader utiliza esse user para criar o avatar.
- Criação do sidebar;
- Criação do header;
- [x ] I have performed a self-review of my …
> Integrações sidebar e header

- src/interface/UserInterface.ts
- src/pages/CreatePostPage/CreatePostPage.tsx
- src/service/Post.ts
- [ X] New feature (non-breaking change which adds functionality)
- Foi integrado o a rota para criação de post;
- Foi iniciada a integração para a rota de Get de postagens;
...
- Página de criação de postagem
- npm run dev
> Integração do Create Post 

- src/components/Sidebar/Sidebar.tsx
- src/pages/CreatePostPage/CreatePostPage.tsx
- src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
- src/pages/LoginPage/LoginPage.tsx
- src/pages/RegisterPage/RegisterPage.tsx
- src/theme/theme.tsx
- [ x] Bug fix (non-breaking change which fixes an issue)
- Mudança na cor do bg dos inputs;
- Mudança na altura do registro;
- Mudança de top={0} para top="90px".
- Alterações
- [x ] My changes have less than or equal 400 lines
- [x ] I have performed a self-review of my own code
- npm install
> Ajustes nos inputs

- src/components/Sidebar/NavItem.tsx
- src/interface/UserInterface.ts
- src/pages/CreatePostPage/CreatePostPage.tsx
- src/pages/ResetPassword/ResetPasswordPage.tsx
- src/routes/MainRoutes.tsx
- src/routes/index.tsx
- src/service/Auth.ts
- src/theme/theme.tsx
- [x ] New feature (non-breaking change which adds functionality)
-Adição de tags na criação de postagens;
-Ajustes no botão de postagem com os padrões dos outros;
cad)
enshots
- [x ] My changes have less than or equal 400 lines
- [ x] I have performed a self-review of my own code
- [x ] The existing tests and linter pass locally with my changes
> adição de tags

- src/components/Sidebar/NavItem.tsx
- src/components/Sidebar/Sidebar.tsx
- src/components/Sidebar/SidebarContent.tsx
- src/components/Sidebar/SidebarHeader.tsx
- src/components/Sidebar/linkItems.ts
- src/interface/SideBarInterface.ts
- src/interface/UserInterface.ts
- src/pages/CreatePostPage/CreatePostPage.tsx
As interfaces do sidebar foram retiradas dos componentes e colocadas em um arquivo SideBarInterface.ts
- [x ] My changes have less than or equal 400 lines
- [ x] I have performed a self-review of my own code
> Interfaces Sidebar

- src/pages/PostPage/PostPage.tsx
- src/theme/theme.tsx
- [ X ] New feature (non-breaking change which adds functionality)
Esqueleto da PostPage apenas para as integrações, depois o layout vai ser finalizado certinho.
obs: Fiz o mobile first e depois irei ajustar o desktop.
...
...
- [ X ] My changes have less than or equal 400 lines
> Finalização do esqueleto da PostPage

- src/interface/UserInterface.ts
- src/pages/ResetPassword/ResetPasswordPage.tsx
- src/routes/MainRoutes.tsx
- src/service/Auth.ts
- [ x] New feature (non-breaking change which adds functionality)
- interação do forgot-password pronto;
- integração do reset-password pronto;
...
...
> reset-password

- src/pages/UsersPage/UsersPage.tsx
Este pull request adiciona uma nova funcionalidade de paginação e barra de pesquisa na página de Usuários, utilizando componentes do Chakra UI para facilitar a navegação e busca de usuários no sistema.
N/A
N/A
> Paginação e buscas do users

- src/components/PostCard/PostCard.tsx
Correção de bug na exibição do postcard
bug: na barra de search o postCard as vezes não era exibido e quebrava a renderização da página
> Fix: exibição do PostCard sem bug de description

- src/components/Sidebar/Sidebar.tsx
Correção do bug do botão de logout, o botão é exibido com o token de acesso
Bug: o botão de logout não aparecia em casos de o login ser realizado, mas o get my-profile não, impossibilitando de realizar o logout para tentar novamente
...
> Fix: botão de logout aparece mesmo com erro no get my-profile

- src/components/Sidebar/SidebarContent.tsx
- src/components/Sidebar/SidebarHeader.tsx
- src/components/Sidebar/linkItems.ts
- src/routes/MainRoutes.tsx
- src/routes/index.tsx
Deleção de botão de posts do menu
navigate para o my-profile ao clicar no avatar
navigate para a home page ao clicar na logo
> Adjustments

- src/components/Sidebar/linkItems.ts
- src/pages/TagsListPage/TagsListPage.tsx
- src/routes/MainRoutes.tsx
- src/routes/index.tsx
> Feat: rota de TagsList

- package.json
- src/components/Notifications/NotificationItem.tsx
- src/components/Notifications/NotificationsBox.tsx
- src/components/Notifications/NotificationsWrapper.tsx
- src/interface/UserInterface.ts
- src/service/Notifications.ts
Integração das notificações com o backend
- [x My changes have less than or equal 400 lines
> Feat: integração das notifications com o back

- src/components/MenuPostComponent/MenuPostComponent.tsx
- src/pages/PostPage/PostPage.tsx
- src/store/postStore.ts
- [x ] Bug fix (non-breaking change which fixes an issue)
-zustand atualiza o status_open
...
...
> fix: zustand atualiza o status_open

- src/components/CommentList/CommentList.tsx
- src/interface/CommentsInterface.ts
- src/interface/UserInterface.ts
- src/pages/PostPage/PostPage.tsx
- src/service/Like.ts
- src/store/commentStore.ts
- src/store/postStore.ts
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- like de post;
- like de comentário;
...
...
> like e unlike

- src/pages/TagsListPage/TagsListPage.tsx
- src/pages/TagsPage/TagsPage.tsx
- src/service/Post.ts
Desenvolvido e corrigido as páginas de tags.
N/A
N/A
> Páginas de Tags

- src/pages/TagsListPage/TagsListPage.tsx
- src/pages/TagsPage/TagsPage.tsx
Adicionada funcionalidade para seguir e deixar de seguir tags na página de tags.
N/A
N/A
> Seguir tags

- src/pages/HomePage/HomePage.tsx
- src/service/Post.ts
> Feat: posts por tags seguidas na home page

- src/components/Section/Section.tsx
- src/pages/HomePage/HomePage.tsx
- src/pages/TagsPage/TagsPage.tsx
> Fix: overflowX hidden no section

- src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
- src/pages/LoginPage/LoginPage.tsx
- src/pages/RegisterPage/RegisterPage.tsx
- src/pages/ResetPassword/ResetPasswordPage.tsx
- src/routes/index.tsx
> Styles: ajuste de margem nas páginas de autenticação
